version: '3.5'
services:
  app:
    #build: .
    image: pw0k/workoutbot:latest
    environment:
      #JAVA_TOOL_OPTIONS: -Xmx300M -Xms250M -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=100M -XX:ReservedCodeCacheSize=32M -Xss192K
      JAVA_TOOL_OPTIONS: -Xmx200M
      WORKOUT_DATASOURCE_URL: ${WORKOUT_DATASOURCE_URL}
      WORKOUT_DB_USER: ${WORKOUT_DB_USER}
      WORKOUT_DB_PASSWORD: ${WORKOUT_DB_PASSWORD}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_TEST_CHAT: ${TELEGRAM_TEST_CHAT}
      TELEGRAM_GENERAL_CHAT: ${TELEGRAM_GENERAL_CHAT}
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8090:8080"
  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: workoutdb
      POSTGRES_USER: ${WORKOUT_DB_USER}
      POSTGRES_PASSWORD: ${WORKOUT_DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
