spring:
  datasource:
    url: ${WORKOUT_DATASOURCE_URL}
    username: ${WORKOUT_DB_USER}
    password: ${WORKOUT_DB_PASSWORD}
    #trying to optimize memory
    hikari:
      maximum-pool-size: 5
    #show-sql: true
    #hibernate:
    #  ddl-auto: validate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    lazy-initialization: true
  liquibase:
    change-log: classpath:db/changelog.sql

telegram:
  botName: workoutPwBot
  token: ${TELEGRAM_TOKEN}
  testChat: ${TELEGRAM_TEST_CHAT}

#trying to optimize memory
server:
  tomcat:
    threads:
      max: 10