name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      WORKOUT_DATASOURCE_URL: jdbc:postgresql://localhost:5432/workoutdb
      WORKOUT_DB_USER: dummy
      WORKOUT_DB_PASSWORD: dummy
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_TEST_CHAT: 666
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Print environment variables
        run: env

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker Image
        run: ./gradlew bootBuildImage

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          push: true
#          tags: pw0k/workoutbot:latest

      - name: Push Docker image to Docker Hub
      #  run: docker push workoutbot:latest
        run: docker push pw0k/workoutbot:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull workoutbot:latest
            docker-compose up -d