name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      WORKOUT_DATASOURCE_URL: jdbc:postgresql://localhost:54/workoutdb
      WORKOUT_DB_USER: dummy
      WORKOUT_DB_PASSWORD: dummy
      TELEGRAM_TOKEN: TELEGRAM_TOKEN
      TELEGRAM_TEST_CHAT: 666
      TELEGRAM_GENERAL_CHAT: 666
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 7.6
      - name: Run build with Gradle Wrapper
        run: ./gradlew build  --scan --warning-mode all



#      - name: Execute Gradle build
#        uses: ./gradlew build --scan
#
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v3

      # https://paketo.io/docs/reference/java-reference/
      # todo как варик грузить в артифактори actions или собирать силами docker
      # мб будет эффективней и получиится сократить использование ram на VPS
#      - name: Build Docker Image
#        run: ./gradlew bootBuildImage

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

#      - name: Push Docker image to Docker Hub
#        run: docker push pw0k/workoutbot:latest
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: pw0k/workoutbot-bot:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            mkdir -p /opt/workoutbot
            cd /opt/workoutbot
            
            # Create .env file from GitHub Secrets
            rm -rf .env
            echo "WORKOUT_DATASOURCE_URL=${{ secrets.WORKOUT_DATASOURCE_URL }}" >> .env
            echo "WORKOUT_DB_USER=${{ secrets.WORKOUT_DB_USER }}" >> .env
            echo "WORKOUT_DB_PASSWORD=${{ secrets.WORKOUT_DB_PASSWORD }}" >> .env
            echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env
            echo "TELEGRAM_TEST_CHAT=${{ secrets.TELEGRAM_TEST_CHAT }}" >> .env
            echo "TELEGRAM_GENERAL_CHAT=${{ secrets.TELEGRAM_GENERAL_CHAT }}" >> .env
            
            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -O https://raw.githubusercontent.com/pw0k/workoutbot/main/docker-compose.yml
            
            docker pull pw0k/workoutbot:latest
            docker-compose down
            docker-compose up -d